### ISSUE TITLE
The fixed transparent navbar at the top looks ugly while scrolling

### ISSUE THREAD

**Issue by jebinphilipose** [yash2code/yash2code.github.io#2]
I would like to make some changes to this so that your page looks great.

**Comment by yash2code** [comment]
@jebinphilipose  Cool ! You're most welcome to fix it :D

**Comment by jebinphilipose** [comment]
Either the navbar should not be fixed on the viewport or the color should be changed so that when the background color becomes white on the viewport while scrolling, your name and your social links are visible.

**Comment by yash2code** [comment]
@jebinphilipose I think color needs to be changed so that visiting social links will be handy :grin:

**Comment by Sarthakagarwal22** [comment]
I would also like to contribute to the project.What can be done is that the navbar can be made invisible after the page is scrolled till the black background.Then the navbar is visible when we scroll up and hides when we scroll down.Also the color can be changed to black with a 30-40% opacity

**Comment by yash2code** [comment]
@Sarthakagarwal22 Interesting ...Send pr I ll review it :blush:

**Comment by jebinphilipose** [comment]
Please review my PR (#3).

**Comment by Sarthakagarwal22** [comment]
Please review my PR [(#4)](https://github.com/yash2code/yash2code.github.io/pull/4). You can change the color of the navbar to anything you like by simply changing it in the custom css file.I made it according to the color scheme
